### ISSUE TITLE
blank page when running autograph_front_end

### ISSUE THREAD

**Issue by jiaxings** [GuitarmonYz/AutoKnowledge#1]
Hello,is the autograph_front_end runable? I tried it with npm run dev but got the blank page.

**Comment by GuitarmonYz** [comment]
please try the vue_front_end folder, the code in autograh_front_end has not been completed

**Comment by Yujie-Ren123** [comment]
Hello, could you please indicate that how to run  vue_front_end folder? Thank you!

**Comment by GuitarmonYz** [comment]
HI,

Under vue_front_end folder, you basically start the app like an ordinary
vue app, try npm start or npm run. You will also want to set up the
database and start the backend before running the front end.
The project is a pretty much outdated to today's design pattern, but thank
you for reaching out.

Best,
Joe

**Comment by Yujie-Ren123** [comment]
Thank you for your response! Under the vue_front_end folder I've tried "npm start" and "npm run" but it doesn't work. It says "npm ERR! missing script: start"  and "Error: no test specified". So would you please teach me what I'm suppose to do? Thank you!
By the way, my backend also have some problems. Here's what the message is: "for relationship in raw_json['results'][0]['data']: KeyError: 'results'". Is this because I hadn't get the data from neo4j first?
I'm recently learning neo4j and its visualization and your project and help means pretty much to me. Thank you again!

**Comment by GuitarmonYz** [comment]
Maybe try npm run dev

**Comment by Yujie-Ren123** [comment]
Hello! I've tried "npm run dev", "npm run", "npm start" but none of them worked. It said: "missing script: dev", "missing script: test", and "Error: no test specified". I think there's something wrong with the files in the vue_fromt_end. It's structure doesn't seem like a standard vue.js program. So I'm having a problem here. Could you please help me out? Thank you! And there's no problem with the back end now.

**Comment by GuitarmonYz** [comment]
Dude, this project I haven't run it for serval years, it's your job to
figure it out, it's written when vue.js just came out, I'm not at all
surprised that it's different from today's vue app
